# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

# version format
version: 1.0.{build}

# Build worker image (VM template)
image: Visual Studio 2017

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Win32

# build Configuration, i.e. Debug, Release, etc.
configuration: Debug

# scripts that run after cloning repository
install:
  # Download extra libs
  - ps: echo "Download extra libs..."
  - ps: if (!(Test-Path 'extra_libs')) { mkdir 'extra_libs' }
  - ps: pushd extra_libs
  - ps: if (!(Test-Path 'sdk')) { Invoke-WebRequest http://yadoms.com/appveyor_build/win32/plugin-SDK-windows-2.1.0-beta.1.zip -OutFile sdk.zip; 7z x sdk.zip -bso0 }
  - ps: rm sdk.zip
  - ps: popd    
  - ps: echo "[END] install"

# scripts to run before build
before_build:  
  # Yadoms configuration file
  - ps: echo "Create Yadoms configuration file CMakeListsUserConfig.txt..."
  - ps: $cd_for_cmake="$pwd".Replace("\", "/")
  - ps: echo $cd_for_cmake
  - ps: Set-Content 'CMakeListsUserConfig.txt' ('set(YADOMS_PLUGIN_SDK_ROOT "' + $cd_for_cmake + '/extra_libs/sdk")')
  - ps: cat 'CMakeListsUserConfig.txt'

  # Create solution
  - ps: echo "Create solution..."
  - cmd: cmake_windows.cmd
  
  
build:
  parallel: false
  project: projects/plugin.EnOcean.sln

  # MSBuild verbosity level
  verbosity: normal

  
notifications:
  - provider: Email
    subject: 'Build {{status}}: {{projectName}}, branch {{branch}}, {{buildVersion}}'
    to:
      - '{{commitAuthorEmail}}'
    on_build_status_changed: true
  